#!/bin/sh

. /lib/lsb/init-functions

FRED_PATH=/usr/sbin
RIFD_PORT=2222
PIFD_PORT=2223
ADIFD_PORT=2224
OPTIONS="-ORBnativeCharCodeSet UTF-8 -ORBendPoint giop:tcp::"

MSG_START="Starting FRED central registry CORBA servers..."
MSG_STOP="Stopping FRED central registry CORBA servers..."

# set DB_INIT=0 if you have your own database setup (database name,
# database user, access rules..etc)
DB_INIT=1
DB_FILE="/usr/sbin/fred-dbmanager"

fred_start() {
    if [ $DB_INIT -eq 1 -a -x $DB_FILE ]
    then
	# this script will ensure that database exists
	/bin/su - postgres -c "$DB_FILE install"
	if [ $? -ne 0 ]; then exit 1; fi
    fi
    /usr/bin/pyfredctl start > /dev/null
    ${FRED_PATH}/fred-rifd ${OPTIONS}${RIFD_PORT} 2>/dev/null &
    ${FRED_PATH}/fred-pifd ${OPTIONS}${PIFD_PORT} 2>/dev/null &
    ${FRED_PATH}/fred-adifd ${OPTIONS}${ADIFD_PORT} 2>/dev/null &
    if [ $? != 0 ]; then
	log_failure_msg ${MSG_START}
    else
	log_success_msg ${MSG_START}
    fi
}

fred_stop() {
    /usr/bin/killall fred-rifd 2>/dev/null
    /usr/bin/killall fred-pifd 2>/dev/null
    /usr/bin/killall fred-adifd 2>/dev/null
    /usr/bin/pyfredctl stop > /dev/null
    log_success_msg ${MSG_STOP}
}
case "$1" in
start)
	fred_start
  ;;
restart)
	fred_stop
	fred_start
  ;;
stop)
	fred_stop
  ;;
*)
  log_success_msg "Usage: /etc/init.d/fred-server {start|stop|restart}"
  exit 1
esac

exit 0
