stages:
  - image
  - analysis
  - build

.image: &image
  stage: image
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull "$IMAGE_TAG" || true
    - docker build --cache-from "$IMAGE_TAG" -t "$IMAGE_TAG" "scripts/docker/$IMAGE_NAME" || docker build --no-cache -t "$IMAGE_TAG" "scripts/docker/$IMAGE_NAME"
    - docker push "$IMAGE_TAG"
  tags:
    - dind
    - old

docker:server:ubuntu:
  <<: *image
  variables:
    IMAGE_NAME: ubuntu:16.04
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME

docker:server:fedora:
  <<: *image
  variables:
    IMAGE_NAME: fedora:27
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME
  only:
    - master
    - triggers
    - schedules
    - web

docker:server:centos:
  <<: *image
  variables:
    IMAGE_NAME: centos:7
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME
  only:
    - master
    - triggers
    - schedules
    - web

.ubuntu_16_04: &ubuntu_16_04
  image: "$CI_REGISTRY/fred/server/ubuntu:16.04"
  tags:
    - amd64
    - builder
    - linux

.fedora_27: &fedora_27
  image: "$CI_REGISTRY/fred/server/fedora:27"
  tags:
    - amd64
    - builder
    - linux

.centos_7: &centos_7
  image: "$CI_REGISTRY/fred/server/centos:7"
  tags:
    - amd64
    - builder
    - linux

.build: &build_job
  variables:
    SRC_DIR: /usr/local/env
  stage: build
  before_script:
    - echo "\$SRC_DIR=$SRC_DIR"
    - echo "\$HOME=$HOME"
    - install -m 700 -d $HOME/.ssh
    - install -m 600 $SRC_DIR/{id_rsa,id_rsa.pub,known_hosts} $HOME/.ssh/
    - GIT_UPSTREAM=$(git config remote.origin.url | cut -d/ -f-3 | sed 's$https://.*@$ssh://git@$')
    - echo "\$GIT_UPSTREAM=$GIT_UPSTREAM"
    - while read -r repo commit clone_path ; do [[ ! x"$repo" = x"#" ]] && git clone "$GIT_UPSTREAM"/"$repo" --single-branch --depth 1 --branch "$commit" "$clone_path" ; done < dependencies.txt

build:ubuntu:amd64:
  <<: *ubuntu_16_04
  <<: *build_job
  script:
    - echo "\$PWD=$PWD"
    - DISTCHECK_CMAKE_FLAGS=-DPostgreSQL_ADDITIONAL_VERSIONS=9.6 cmake -DPostgreSQL_ADDITIONAL_VERSIONS=9.6 -DIDL_DIR=/builds/fred/server/external/idl/idl .
    - make -j $(($(grep -c processor /proc/cpuinfo) / 2 + 1)) distcheck

build:fedora:amd64:
  <<: *fedora_27
  <<: *build_job
  script:
    - echo "\$PWD=$PWD"
    - cmake -DIDL_DIR=/builds/fred/server/idl/idl .
    - make -j $(($(grep -c processor /proc/cpuinfo) / 2 + 1)) distcheck
  only:
    - master
    - triggers
    - schedules
    - web

build:centos:amd64:
  <<: *centos_7
  <<: *build_job
  script:
    - echo "\$PWD=$PWD"
    - cmake3 -DIDL_DIR=/builds/fred/server/idl/idl .
    - make -j $(($(grep -c processor /proc/cpuinfo) / 2 + 1)) distcheck
  only:
    - master
    - triggers
    - schedules
    - web

licensing:
  <<: *ubuntu_16_04
  variables:
    SRC_DIR: /usr/local/env
  stage: analysis
  before_script:
    - echo "\$SRC_DIR=$SRC_DIR"
    - echo "\$HOME=$HOME"
    - install -m 700 -d $HOME/.ssh
    - install -m 600 $SRC_DIR/{id_rsa,id_rsa.pub,known_hosts} $HOME/.ssh/
    - git clone git@gitlab.office.nic.cz:internal-tools/license-check.git --single-branch --depth 1
  script:
    - ./license-check/license-check.sh -v
