stages:
  - image
  - build

.image: &image
  stage: image
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull "$IMAGE_TAG" || true
    - docker build --cache-from "$IMAGE_TAG" -t "$IMAGE_TAG" "scripts/docker/$IMAGE_NAME"
    - docker push "$IMAGE_TAG"
  tags:
    - dind

docker:server:ubuntu:
  <<: *image
  variables:
    IMAGE_NAME: ubuntu:latest
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME

docker:server:fedora:
  <<: *image
  variables:
    IMAGE_NAME: fedora:latest
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME

.ubuntu_latest: &ubuntu_latest
  image: "$CI_REGISTRY/fred/server/ubuntu:latest"
  tags:
    - amd64

.fedora_latest: &fedora_latest
  image: "$CI_REGISTRY/fred/server/fedora:latest"
  tags:
    - amd64

.build: &build_job
  stage: build
  before_script:
    - /usr/local/env/setup
  script:
    - autoreconf -vfi
    - git clone git@gitlab.office.nic.cz:fred/idl.git
    # TODO: checkout branch
    - ./configure --with-idldir=./idl/idl || ( cat config.log && exit 1 )
    # TODO: distcheck
    - make -j5

build:ubuntu:amd64:
  <<: *ubuntu_latest
  <<: *build_job

build:fedora:amd64:
  <<: *fedora_latest
  <<: *build_job
