// reason message
#define REASON_MSG_BAD_FORMAT_CONTACT_HANDLE  1 
#define REASON_MSG_BAD_FORMAT_NSSET_HANDLE    2 
#define REASON_MSG_BAD_FORMAT_FQDN 3 
#define REASON_MSG_NOT_APPLICABLE_FQDN 4

#define REASON_MSG_BAD_PERIOD 100 
#define REASON_MSG_BAD_VALEXPDATE  101 
#define REASON_MSG_BAD_IP_ADDRESS 102 
#define REASON_MSG_CAN_NOT_ADD_STATUS 103 
#define REASON_MSG_CAN_NOT_REM_STATUS  104 
#define REASON_MSG_CUREXPDATE_NOT_EXPDATE 105 

#define REASON_MSG_BAD_DNS_NAME  400
#define REASON_MSG_REASON_MSG_DUPLICITY_IP_ADDRESS 401 
#define REASON_MSG_DNS_NAME_NOTEXIST 402 
#define REASON_MSG_DNS_NAME_EXIST 403 
#define REASON_MSG_MIN_DNS 404 
#define REASON_MSG_NOT_ANY_DNS 405 
#define REASON_MSG_NOT_ANY_TECH 406 
#define REASON_MSG_IP_GLUE_NOT_ALLOWED 407 
#define REASON_MSG_CAN_NOT_REMOVE_TECH 408 
#define REASON_MSG_CAN_NOT_REMOVE_DNS 409 
#define REASON_MSG_CAN_NOT_REM_DNS 410 
#define REASON_MSG_CAN_NOT_ADD_DNS 411 


#define REASON_MSG_VALEXPDATE_REQUIRED     501
#define REASON_MSG_VALEXPDATE_NOT_VALID    502
#define REASON_MSG_VALEXPDATE_NOT_USED     503
 
#define REASON_MSG_NSSET_EXIST 901 
#define REASON_MSG_NSSET_NOTEXIST 902 
#define REASON_MSG_NSSET_HISTORY 903 

#define REASON_MSG_CONTACT_EXIST 911 
#define REASON_MSG_CONTACT_NOTEXIST 912 
#define REASON_MSG_CONTACT_HISTORY 913 

#define REASON_MSG_FQDN_EXIST  921 
#define REASON_MSG_FQDN_NOTEXIST  922 
#define REASON_MSG_FQDN_HISTORY 923 


#define REASON_MSG_REGISTRANT_NOTEXIST 1100  

#define REASON_MSG_ADMIN_EXIST 1001 
#define REASON_MSG_ADMIN_NOTEXIST 1003 

#define REASON_MSG_TECH_EXIST 1011 
#define REASON_MSG_TECH_NOTEXIST 1013 

#define REASON_MSG_UNKNOW_REGISTRANT  1101 
#define REASON_MSG_UNKNOW_NSSET 1102 
#define REASON_MSG_UNKNOW_ADMIN 1103 
#define REASON_MSG_UNKNOW_TECH 1104 
#define REASON_MSG_UNKNOW_COUNTRY 1105 
#define REASON_MSG_UNKNOW_MSGID  1106 
