#define    COMMAND_OK     1000
#define    COMMAND_LOGOUT 1500
#define    COMMAND_FAILED 2400
#define COMMAND_OBJECT_NOT_EXIST 2303
#define COMMAND_OBJECT_EXIST    2302
#define COMMAND_AUTH_ERROR    2501
#define COMMAND_AUTOR_ERROR    2201

#define COMMAND_NO_MESG  1300 // nejsou zadne zpravi vraci poll 
#define COMMAND_ACK_MESG 1301 // zpravy jsou ve fronte vraci poll

#define COMMAND_STATUS_PROHIBITS_OPERATION 2304
#define COMMAND_PROHIBITS_OPERATION 2305
