#!/bin/sh
time epp_client > log01 &
time epp_client > log02 &
time epp_client > log03 &
time epp_client > log04 &
time epp_client > log05 &
time epp_client > log06 &
time epp_client > log07 &
time epp_client > log08 &
time epp_client > log09 &
time epp_client > log11 &
time epp_client > log12 &
time epp_client > log13 &
time epp_client > log14 &
time epp_client > log15 &
time epp_client > log16 &
time epp_client > log17 &
time epp_client > log18 &
time epp_client > log19 &
time epp_client > log20 &
time epp_client > log21 &
time epp_client > log22 &
time epp_client > log23 &
time epp_client > log24 &
time epp_client > log25 &
