#define REASON_MSG_BAD_FORMAT_CONTACT_HANDLE  1 
#define REASON_MSG_BAD_FORMAT_NSSET_HANDLE    2 
#define REASON_MSG_BAD_FORMAT_FQDN 3 
#define REASON_MSG_NOT_APPLICABLE_DOMAIN 4

#define REASON_MSG_MSGID_NOTEXIST  17

// for mod_eppd through through GetTransaction function 
#define REASON_MSG_TRANSFER_OP 33
#define REASON_MSG_CONTACT_IDENTTYPE_MISSING 34
#define REASON_MSG_POLL_MSGID_MISSING  35

#define REASON_MSG_XML_VALIDITY_ERROR 37

#define REASON_MSG_BAD_FORMAT_KEYSET_HANDLE   39
