/*
 * Copyright (C) 2013  CZ.NIC, z.s.p.o.
 *
 * This file is part of FRED.
 *
 * FRED is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * FRED is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FRED.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *  @file
 *  nsset info
 */

#ifndef INFO_NSSET_H_
#define INFO_NSSET_H_

#include <string>
#include <vector>
#include <set>

#include <boost/date_time/posix_time/ptime.hpp>
#include <boost/date_time/gregorian/gregorian.hpp>

#include "fredlib/opexception.h"
#include "fredlib/opcontext.h"
#include "util/optional_value.h"
#include "util/db/nullable.h"
#include "util/printable.h"

#include "fredlib/nsset/info_nsset_data.h"
#include "fredlib/nsset/info_nsset_history.h"


namespace Fred
{
    /**
    * Nsset info data structure.
    */
    struct InfoNssetOut : public Util::Printable
    {
        InfoNssetData info_nsset_data;/**< data of the nsset */
        boost::posix_time::ptime utc_timestamp;/**< timestamp of getting the nsset data in UTC */
        boost::posix_time::ptime local_timestamp;/**< timestamp of getting the nsset data in local time zone viz @ref local_timestamp_pg_time_zone_name */

        /**
         * Empty constructor.
         */
        InfoNssetOut()
        {}

        /**
        * Equality of the nsset data structure.
        * Compares only data of the nsset @ref info_nsset_data, not the timestamps.
        * @param rhs is right hand side of the nsset data comparison
        * @return true if equal, false if not
        */

        bool operator==(const InfoNssetOut& rhs) const
        {
            return info_nsset_data == rhs.info_nsset_data;
        }

        /**
        * Inequality of the nsset data structure.
        * Compares only data of the nsset @ref info_nsset_data, not the timestamps.
        * @param rhs is right hand side of the nsset data comparison
        * @return true if not equal, false if equal
        */
        bool operator!=(const InfoNssetOut& rhs) const
        {
            return !this->operator ==(rhs);
        }

        /**
        * Dumps state of the instance into the string
        * @return string with description of the instance state
        */
        std::string to_string() const;
    };


    /**
    * Info of nsset.
    * Nsset fully qualified name to get info about is set via constructor.
    * Info is executed by @ref exec method with database connection supplied in @ref OperationContext parameter.
    * When exception is thrown, changes to database are considered incosistent and should be rolled back by the caller.
    * In case of wrong input data or other predictable and superable failure, the instance of @ref OldInfoNsset::Exception is thrown with appropriate attributes set.
    * In case of other unsuperable failures and inconstistencies, the instance of @ref InternalError or other exception is thrown.
    */
    class OldInfoNsset  : public Util::Printable
    {
        const std::string handle_;/**< nsset identifier */
        bool lock_;/**< lock object_registry row flag*/
    public:
        DECLARE_EXCEPTION_DATA(unknown_nsset_handle, std::string);/**< exception members for unknown nsset handle generated by macro @ref DECLARE_EXCEPTION_DATA*/
        struct Exception
        : virtual Fred::OperationException
        , ExceptionData_unknown_nsset_handle<Exception>
        {};

        /**
        * Info nsset constructor with mandatory parameter.
        * @param handle sets nsset identifier into @ref handle_ attribute
        */
        OldInfoNsset(const std::string& handle);

        /**
        * Sets nsset lock flag.
        * @param lock sets lock nsset flag into @ref lock_ attribute
        * @return operation instance reference to allow method chaining
        */
        OldInfoNsset& set_lock(bool lock = true);

        /**
        * Executes getting info about the nsset.
        * @param ctx contains reference to database and logging interface
        * @param local_timestamp_pg_time_zone_name is postgresql time zone name of the returned data
        * @return info data about the nsset
        */
        InfoNssetOut exec(OperationContext& ctx, const std::string& local_timestamp_pg_time_zone_name = "Europe/Prague");

        /**
        * Dumps state of the instance into the string
        * @return string with description of the instance state
        */
        std::string to_string() const;
    };//class OldInfoNsset

}//namespace Fred

#endif//INFO_NSSET_H_
