FROM ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update
RUN apt-get -y dist-upgrade
RUN apt-get -y install               \
        autoconf                     \
        automake                     \
        autotools-dev                \
        autoconf-archive             \
        pkg-config                   \
        libtool                      \
        build-essential              \
        bash-completion              \
        git                          \
        libomniorb4-dev              \
        omniidl                      \
        omniidl-python               \
        omniorb                      \
        omniorb-idl                  \
        omniorb-nameserver           \
        libboost-date-time-dev       \
        libboost-program-options-dev \
        libboost-regex-dev           \
        libboost-filesystem-dev      \
        libboost-random-dev          \
        libboost-thread-dev          \
        libboost-system-dev          \
        libboost-serialization-dev   \
        libboost-test-dev            \
        libpq-dev                    \
        libcurl4-openssl-dev         \
        libmpdec-dev                 \
        libssh-dev                   \
        libminizip-dev               \
        libxml2-dev                  \
        libidn11-dev
