/*
 * Copyright (C) 2013  CZ.NIC, z.s.p.o.
 *
 * This file is part of FRED.
 *
 * FRED is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * FRED is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FRED.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *  @file
 *  domain info
 */

#ifndef INFO_DOMAIN_H_
#define INFO_DOMAIN_H_

#include <string>
#include <vector>
#include <set>

#include <boost/date_time/posix_time/ptime.hpp>
#include <boost/date_time/gregorian/gregorian.hpp>

#include "fredlib/opexception.h"
#include "fredlib/opcontext.h"
#include "util/optional_value.h"
#include "util/db/nullable.h"

#include "fredlib/domain/info_domain_data.h"

namespace Fred
{
    /**
    * Domain info data structure.
    */
    struct InfoDomainOutput
    {
        InfoDomainData info_domain_data;/**< data of the domain */
        boost::posix_time::ptime utc_timestamp;/**< timestamp of getting the domain data in UTC */
        boost::posix_time::ptime local_timestamp;/**< timestamp of getting the domain data in local time zone viz @ref local_timestamp_pg_time_zone_name */

        /**
        * Empty constructor of the domain data structure.
        */
        InfoDomainOutput()
        {}

        /**
        * Equality of the domain data structure.
        * Compares only data of the domain @ref info_domain_data, not the timestamps.
        * @param rhs is right hand side of the domain data comparison
        * @return true if equal, false if not
        */
        bool operator==(const InfoDomainOutput& rhs) const
        {
            return info_domain_data == rhs.info_domain_data;
        }
        /**
        * Inequality of the domain data structure.
        * Compares only data of the domain @ref info_domain_data, not the timestamps.
        * @param rhs is right hand side of the domain data comparison
        * @return true if not equal, false if equal
        */
        bool operator!=(const InfoDomainOutput& rhs) const
        {
            return !this->operator ==(rhs);
        }

    };

    /**
    * Info of domain.
    * Domain fully qualified name to get info about is set via constructor.
    * Info is executed by @ref exec method with database connection supplied in @ref OperationContext parameter.
    * When exception is thrown, changes to database are considered incosistent and should be rolled back by the caller.
    * In case of wrong input data or other predictable and superable failure, the instance of @ref InfoDomain::Exception is thrown with appropriate attributes set.
    * In case of other unsuperable failures and inconstistencies, the instance of @ref InternalError or other exception is thrown.
    */
    class InfoDomain
    {
        const std::string fqdn_;/**< fully qualified domain name */
        bool lock_;/**< lock object_registry row flag*/

    public:

        DECLARE_EXCEPTION_DATA(unknown_domain_fqdn, std::string);/**< exception members for unknown fully qualified domain name, generated by macro @ref DECLARE_EXCEPTION_DATA */

        struct Exception
        : virtual Fred::OperationException
        , ExceptionData_unknown_domain_fqdn<Exception>
        {};

        /**
        * Info domain constructor with mandatory parameter.
        * @param fqdn sets fully qualified domain name into @ref fqdn_ attribute
        */
        InfoDomain(const std::string& fqdn);

        /**
        * Sets domain lock flag.
        * @param lock sets lock domain flag into @ref lock_ attribute
        * @return operation instance reference to allow method chaining
        */
        InfoDomain& set_lock(bool lock = true);

        /**
        * Executes getting info about the domain.
        * @param ctx contains reference to database and logging interface
        * @param local_timestamp_pg_time_zone_name is postgresql time zone name of the returned data
        * @return info data about the domain
        */
        InfoDomainOutput exec(OperationContext& ctx, const std::string& local_timestamp_pg_time_zone_name = "Europe/Prague");

        /**
        * Dumps state of the instance into stream
        * @param os contains output stream reference
        * @param i reference of instance to be dumped into the stream
        * @return output stream reference
        */
        friend std::ostream& operator<<(std::ostream& os, const InfoDomain& i);

        /**
        * Dumps state of the instance into the string
        * @return string with description of the instance state
        */
        std::string to_string();
    };//class InfoDomain

}//namespace Fred

#endif//INFO_DOMAIN_H_
