/*
 * Copyright (C) 2010  CZ.NIC, z.s.p.o.
 *
 * This file is part of FRED.
 *
 * FRED is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * FRED is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FRED.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *  @hpmail.h
 *  hybrid postservice simple interface header
 */

#ifndef HPMAIL_H_
#define HPMAIL_H_

#include <cstdio>
#include <memory>
#include <vector>
#include <string>

#include <boost/utility.hpp>

#include "hp.h"

/**
 * \class HPMail
 * \brief interface for uploading to hybrid postservice
 *  one instance per process and non-concurrent use only
 *  , using curl easy interface and 7z executable
 */

typedef std::vector<char> MailFile;//one "letter" file data
typedef std::vector<MailFile> MailBatch;//all batch files

class HPMail : boost::noncopyable
{
    std::string mb_proc_tmp_dir_; //temp dir for 7z files ended by slash
    std::string postservice_cert_dir_; //postsignum_qca_root.pem server certificate dir ended by slash
    std::string phpsessid_; //PHP session id
    FILESharedPtr curl_log_file_guard_;//curl log file pointer guard
    std::string hp_interface_url_;// ended by slash like: https://online.postservis.cz/Command/
    std::string hp_batch_number_; // batch number generated by login

    static std::auto_ptr<HPMail> instance_ptr;
    friend class std::auto_ptr<HPMail>;
protected:
    ~HPMail(){}//dtor
private:
    //ctor
    HPMail(const std::string& mb_proc_tmp_dir //tmp dir for 7z files ended by slash
            , const std::string& postservice_cert_dir //postsignum_qca_root.pem server certificate dir ended by slash
            , const std::string& hp_interface_url // ended by slash like: https://online.postservis.cz/Command/
            )
    : mb_proc_tmp_dir_(mb_proc_tmp_dir)
    , postservice_cert_dir_(postservice_cert_dir)
    , phpsessid_("") //initially empty, filled by succesful login
    , curl_log_file_guard_(fopen((mb_proc_tmp_dir+"curl_stderr.log").c_str(),"w"))
    , hp_interface_url_(hp_interface_url)
    , hp_batch_number_("") //initially empty, generated by succesful login
    {}
public:
    static HPMail* set(const std::string& mb_proc_tmp_dir //tmp dir for 7z files ended by slash
            , const std::string& postservice_cert_dir //postsignum_qca_root.pem server certificate dir ended by slash
            , const std::string& hp_interface_url // ended by slash like: https://online.postservis.cz/Command/
            );
    static HPMail* get();

    void login(const std::string& loginame //postservice account name
        , const std::string& password //postservice account password
        , const std::string& batch_id //batch identificator like: "hpcb_Jednorazova_zakazka"
        , const std::string& batch_note //batch note like: "Testovaci prenos!!!" or anything else you need to tell here
        );

    void upload( const MailBatch& mb);


};//class HPMail
#endif // HPMAIL_H_
